name: ultrarag
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- numpy
- scipy
- pandas
- scikit-learn
- matplotlib
- pillow
- opencv
- requests
- httpx
- aiohttp
- websockets
- python-dotenv
- python-json-logger
- python-multipart
- typer
- click
- rich
- tqdm
- tenacity
- tabulate
- parse
- pypdf
- docx2txt
- striprtf
- beautifulsoup4
- lancedb
- ray
- nltk
- spacy
- gensim
- networkx
- plotly
- seaborn
- jupyter
- ipykernel
- ipywidgets
- notebook
- jupyterlab
- streamlit
- gradio
- dash
- bokeh
- altair
- folium
- wordcloud
- textblob
- vaderSentiment
- transformers
- sentence-transformers
- llama-index
- llama-index-core
- llama-index-llms-openai
- llama-index-embeddings-openai
- llama-index-readers-file
- llama-index-workflows
- llama-cloud
- llama-cloud-services
- llama-parse
- fastapi
- uvicorn
- pydantic
- pydantic-settings
- starlette
- sse-starlette
- prometheus-client
- prometheus-fastapi-instrumentator
