name: ultrarag
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.11
- pip
- pytorch-cpu
- torchvision-cpu
- torchaudio-cpu
- cpuonly
- faiss-cpu
- libfaiss
- dirtyjson
- numpy
- scipy
- pandas
- scikit-learn
- matplotlib
- pillow
- opencv
- transformers
- sentence-transformers
- llama-index
- llama-index-core
- llama-index-llms-openai
- llama-index-embeddings-openai
- llama-index-readers-file
- llama-index-workflows
- llama-cloud
- llama-cloud-services
- llama-parse
- fastapi
- uvicorn
- pydantic
- pydantic-settings
- requests
- httpx
- aiohttp
- websockets
- starlette
- sse-starlette
- prometheus-client
- prometheus-fastapi-instrumentator
- python-dotenv
- python-json-logger
- python-multipart
- typer
- click
- rich
- tqdm
- tenacity
- tabulate
- parse
- pypdf
- docx2txt
- striprtf
- beautifulsoup4
- lancedb
- ray
- numba
- llvmlite
- nltk
- sentencepiece
- tokenizers
- tiktoken
- safetensors
- huggingface-hub
- openai
- exa-py
- tavily-python
- mistral-common
- modelscope
- infinity-emb
- llguidance
- lm-format-enforcer
- outlines-core
- compressed-tensors
- einops
- gguf
- hf-transfer
- hf-xet
- griffe
- lark
- interegular
- isodate
- itsdangerous
- jinja2
- markupsafe
- werkzeug
- flask
- sqlalchemy
- psutil
- py-cpuinfo
- pyarrow
- pybase64
- pycountry
- pycparser
- pyparsing
- pyperclip
- pytz
- pyyaml
- pyzmq
- referencing
- regex
- rfc3339-validator
- rich-rst
- rich-toolkit
- rignore
- rouge-score
- rpds-py
- sentry-sdk
- setuptools
- shellingham
- sniffio
- soundfile
- soupsieve
- soxr
- sympy
- threadpoolctl
- typing-inspect
- typing-inspection
- tzdata
- urllib3
- uv
- uvloop
- watchfiles
- wrapt
- yarl
- pip:
  - absl-py==2.3.1
  - aiohappyeyeballs==2.6.1
  - aiosignal==1.4.0
  - aiosqlite==0.21.0
  - annotated-types==0.7.0
  - anyio==4.10.0
  - asgiref==3.9.1
  - astor==0.8.1
  - attrs==25.3.0
  - authlib==1.6.1
  - banks==2.2.0
  - blake3==1.0.5
  - blessed==1.21.0
  - blinker==1.9.0
  - cachetools==6.1.0
  - cbor2==5.6.5
  - certifi==2025.8.3
  - cffi==1.17.1
  - charset-normalizer==3.4.3
  - chonkie==1.1.2
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - contourpy==1.3.3
  - cryptography==45.0.6
  - cycler==0.12.1
  - cyclopts==3.22.5
  - dataclasses-json==0.6.7
  - deprecated==1.2.18
  - deprecation==2.1.0
  - depyf==0.19.0
  - dill==0.4.0
  - diskcache==5.6.3
  - distro==1.9.0
  - dnspython==2.7.0
  - docstring-parser==0.17.0
  - docutils==0.22
  - email-validator==2.2.0
  - fastapi-cli==0.0.8
  - fastapi-cloud-cli==0.1.5
  - fastmcp==2.11.3
  - fastrlock==0.8.3
  - filelock==3.18.0
  - filetype==1.2.0
  - fonttools==4.59.1
  - frozenlist==1.7.0
  - fsspec==2025.7.0
  - greenlet==3.2.4
  - h11==0.16.0
  - httpcore==1.0.9
  - httptools==0.6.4
  - httpx-sse==0.4.1
  - idna==3.10
  - jiter==0.10.0
  - joblib==1.5.1
  - jsonlines==4.0.0
  - jsonschema==4.25.0
  - jsonschema-path==0.3.4
  - jsonschema-specifications==2025.4.1
  - kiwisolver==1.4.9
  - lazy-object-proxy==1.11.0
  - llama-index-agent-openai==0.4.12
  - llama-index-cli==0.4.4
  - llama-index-embeddings-openai==0.3.1
  - llama-index-indices-managed-llama-cloud==0.8.0
  - llama-index-instrumentation==0.4.0
  - llama-index-multi-modal-llms-openai==0.5.3
  - llama-index-program-openai==0.3.2
  - llama-index-question-gen-openai==0.3.1
  - llama-index-readers-file==0.4.8
  - llama-index-readers-llama-parse==0.4.0
  - llama-index-workflows==1.3.0
  - llvmlite==0.44.0
  - markdown-it-py==3.0.0
  - marshmallow==3.26.1
  - mcp==1.12.4
  - mdurl==0.1.2
  - more-itertools==10.7.0
  - mpmath==1.3.0
  - msgpack==1.1.1
  - msgspec==0.19.0
  - multidict==6.6.3
  - mypy-extensions==1.1.0
  - networkx==3.5
  - ninja==1.11.1.4
  - openapi-core==0.19.5
  - openapi-pydantic==0.5.1
  - openapi-schema-validator==0.6.3
  - openapi-spec-validator==0.7.2
  - opencv-python-headless==4.11.*
  - overrides==7.7.0
  - partial-json-parser==0.2.1.1.post6
  - pathable==0.4.4
  - prometheus-client==0.22.1
  - prometheus-fastapi-instrumentator==7.1.0
  - propcache==0.3.2
  - protobuf==6.31.1
  - pydantic-core==2.33.2
  - pydantic-extra-types==2.10.5
  - pydantic-settings==2.10.1
  - python-json-logger==3.3.0
  - python-multipart==0.0.20
  - python-dotenv==1.1.1
  - pyperclip==1.9.0
  - python-multipart==0.0.20
  - typer==0.16.0
  - typing-inspect==0.9.0
  - typing-inspection==0.4.1
  - uv==0.8.8
  - uvicorn==0.35.0
  - uvloop==0.21.0
  - watchfiles==1.1.0
  - websockets==15.0.1
  - werkzeug==3.1.1
  - wrapt==1.17.2
  - yarl==1.20.1
